### ISSUE TITLE
Round up the hash value

### ISSUE THREAD

**Issue by popovae** [jenssegers/imagehash#14]
Hello,

Great class you created and great job done. 
As for sure you already studied the question, maybe you can suggest the best way to accomplish the following:

I need to find a duplicates of images in the database and it is not really good idea to compare 2 images one by one...so I came up with the idea - basically what I want to do is to round a Hash result a little and store it for each image in DB...and later just find duplicated values of Hash. I do understand that the result of this solution will not be comparable to the result I get when calculating the hamming distance, but it is ok for me - I just need to find images that are with 95+% probability are duplicated... 
So, the question is - what is the best place of code to round the Hash? I tried to do it in **ImageHash.php**, but something goes wrong:
```
$hash = round($hash/10)*10;
return $hash;
```
returns some stupid results like 9.23423423423E+34

Any idea what am I doing wrong?

Thank you in advance!!!

**Comment by jenssegers** [comment]
You shouldn't round the hash. Rounding the hash will not add more "fuzziness". The right side of the 64 fingerprint basically corresponds to the last set of pixels of the internal fingerprint. So you're throwing away the information for a small part of the image. There is a bit more information here: https://jenssegers.com/61/perceptual-image-hashes

Just store it and use BIT_COUNT in combination with XOR. If 2 images have exactly the same perceptual hash the chances are high that the are the same. If not, you should count the number of different bits. Beware, for a large set of images you should not use a high threshold for bit differences.

**Comment by popovae** [comment]
Yes, I think I understand the idea behind the hash. But, I have a dataset of 10Mio images... Comparing just in pairs will take ages) So what I was thinking to do is:
Lets assume we have two images with 4ee4b0aba3095800 hash both - this means that with X% possibility this images are the same. Storing the Hash in DB will allow us to simply query DB for aggregation and fastly get the duplicated Hash entries...

What I was thinking is - if I can somehow round the Hash value I will be able to get not just the exact matches, but also "95% probable" matches...

Something like this if to look on it on the bite level:

```
1 image - 10101000000000111100000
2 image - 10101000000000111100001
3 image - 10101000000000111100000

Image 1 = image 2  = 100% match

Now with "rounding":
1 image - 10101000000000111100000
2 image (original) - 10101000000000111100001
2 image ("rounded") - 10101000000000111100000
3 image - 10101000000000111100000

Now 
Image 1 = image 2 = image 3  = 100% match
but we understand that really we lost some information due "rounding" and 
Image 1 +-= image 2 +-= image 3 and now real people will have to check them if they are really the same...
```

**Comment by jenssegers** [comment]
Similar images can have different bits anywhere.

```
1 image - 10101000000000111100000
2 image - 10101000010000111100000
```

The 2 image above are probably the same as well.

**Comment by popovae** [comment]
That is the reason, I was assuming to round $hash - this is an integer number...
Or I'm talking totally stupid thing?))

**Comment by jenssegers** [comment]
Doing `round($hash/10)*10` will basically throw away bits on the right side if the binary string. But that would not work for these 2 very similar images:

```
1 image - 10101000000000111100000
2 image - 10101000010000111100000
```

The 64 bit fingerprint is already highly reduced in information. If you have a 600x800 image, that's about 11.520.000 bits of information right (600*800*3*8)? The only way of "rounding" would be to create a smaller fingerprint holding less information, eg. a 32 bit fingerprint. But then you'll have a much higher chance of having false positives.

**Comment by jenssegers** [comment]
For 10.000.000 images you should still be able to load all of those hashes in memory ~80 megabytes. Just run through them using one or more threads calculating the hamming distance between them. It will do a lot of comparisons, but luckily calculating the hamming distance is a cheap operation.

**Comment by popovae** [comment]
So what you are saying is that using hash as it is will be quite enough to find the duplicates and any rounding will be useless... Got it, thank you for help to understand it! Will dig a little dipper later, will try to run through DB and get hashes first to get some stats, and later will try to figure out how to improve it)) 

Thank you very much for help!)

**Comment by bgaillard** [comment]
Hi, because i'm working on the same problem here are much more informations 
* For MySQL the following post http://stackoverflow.com/questions/14925151/hamming-distance-optimization-for-mysql-or-postgresql explains how to fetch images using `BIT_COUNT` and the XOR operator ; 
* For PostgreSQL the following post explains how to do http://stackoverflow.com/questions/5459487/translate-this-mysql-query-to-pygresql.

We had problems with PostgreSQL because the Percepual Hashes are 64bits length and their maximum size (`18446744073709552000` in decimal) exceeds the size of `BIGINT` type (`9223372036854775807` in decimal).

Perhaps this problem is the same with other databases too. To solve this the trick is to split the Perceptual hashes in 2 columns. Those columns are of type `BIGINT` for PostgreSQL. 

For example if we have an image with a Perceptual Hash equals to `13f06f47a6f80983` we could split it in 2 parts, the first 8 bytes `13f06f47` and the other 8 bytes `a6f80983`. 

Then we convert those 2 values in decimal and obtain `334524231` and `2801273219`, we finally store those values in `phash_1` and `phash_2` columns in our database. 

The final PostgreSQL query is the following (fetching similar images using Hamming Distance of 3 here).

```sql
SELECT *
FROM images
WHERE (
         SELECT  SUM(((phash_1::bigint # 334524231) >> bit) & 1)
         FROM    generate_series(0, 31) bit
      ) 
      + 
      (
         SELECT  SUM(((phash_2::bigint # 2801273216) >> bit) & 1)
         FROM    generate_series(0, 31) bit
      ) <= 3;
```

Hope this helps.

@jenssegers I think this use case is very frequent so it could be great to add a "Database" section in the README of the project. 

What's your opinion about this ?
