### ISSUE TITLE
Switch `phpseclib\Math\BigInteger To Something Lighter

### ISSUE THREAD

**Issue by connerbw** [jenssegers/imagehash#49]
This composer module pulls phplibsec to use `phpseclib\Math\BigInteger`

https://github.com/jenssegers/imagehash/blob/67cf9d71d29db75c6fb251bbcd85b964426886f2/src/Hash.php#L6

https://github.com/jenssegers/imagehash/blob/67cf9d71d29db75c6fb251bbcd85b964426886f2/composer.json#L19

In addition to BigInteger, adding phplibsec to your composer.json brings with it Pure-PHP implementations of SSHv1, SSHv2, SFTP, SCP... None of which is used by imagehash.

Please switch to: https://github.com/brick/math  

Or maybe, copy paste the code you need into your project? It's one file if you comment out:

https://github.com/phpseclib/phpseclib/blob/c78eb5058d5bb1a183133c36d4ba5b6675dfa099/phpseclib/Math/BigInteger.php#L52

The Crypt\Random class is optional:

https://github.com/phpseclib/phpseclib/blob/c78eb5058d5bb1a183133c36d4ba5b6675dfa099/phpseclib/Math/BigInteger.php#L3099

**Comment by GrahamCampbell** [comment]
Why is it necessary to switch? Why does the size of a dependency matter?

**Comment by SmuSmu** [comment]
> Why is it necessary to switch? Why does the size of a dependency matter?

Because it kills trees. Think global : every Bit couts. It saves bandwith. So ist also saves time, Energy, Money ...

Friday for Future

**Comment by trogau** [comment]
> Why is it necessary to switch? Why does the size of a dependency matter?

I have been trying to find time to reply to this because for many people the size of a dependency matters for many many reasons - anyone that has to take security remotely seriously needs to understand exactly what is going on in their dependencies. 

Fortunately this blog post appeared today which I think does a good job explaining how dependency size can matters to some people - it's mostly about licensing issues but it also shows how a security-focused person needs to think about it: https://www.agwa.name/blog/post/always_review_your_dependencies

**Comment by GrahamCampbell** [comment]
What is the problem with the phpspec license?

**Comment by trogau** [comment]
> What is the problem with the phpspec license?

I'm just specifically responding to the question about why dependency size matters, noting that licensing, security, attack surface, etc, are some of the reasons why, to many people, the size of a dependency matters a lot. 

I would guess that for most people, there is no problem with the `phplibsec` license. The point is, to be sure - to be the sort of sure some users need to be before they can include it in a software project - someone would have to (for example) go through the entire project to check each file for licensing terms that could clash with their intended use. The larger the size of the dependency, the more time-consuming a task this is. That's all!

**Comment by VincentChalnot** [comment]
The problem is not that the dependency is too big, the problem is that the dependency is basically useless because there is no actual computation done with BigInteger, it's just here to store the hash which in my opinion could be kept as an array of bits because it's the preferred format to compute a distance between two hashs.
Conversion to hex is useless in my opinion because the hex format can't be used either by PHP or MySQL. (I don't know about bitwise operations on other database platforms though)
Conversion to Int as a string is useful for database storage but can be achieved in a few line of codes.
